version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=mhw-board-companion
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "5050:80"

volumes:
  postgres_data: {}
